<html>
<body>
<h2>Akhil Akkineni was born on 8 April 1994 in San Jose, California, U.S.[1][3] to actors Nagarjuna and Amala. He is of Telugu descent from his father's side, and has Irish and Bengali ancestry from his mother's side.[4] He is the grandson of actor Akkineni Nageswara Rao, and half-brother of Naga Chaitanya.

Akkineni studied at Chaitanya Vidyalaya, later headed to Australia for two years. He returned to complete his studies at Oakridge International School, Hyderabad. He pursued acting as a career at age 16 and enrolled in an acting course at the Lee Strasberg Theatre and Film Institute in New York.[5] He is also a BBA graduate from University of South Florida.[2]

Later in his teens, he pursued cricket and became a member in his father's Nag Kings team, in the 2010 celebrity Tollywood Trophy, which was a fundraiser for the Movie Artistes' Association. His match-winning half-century in the final against Venkatesh's Venky Warriors, saw him secure the man-of-the-match and man-of-the-series awards.[6] His performance saw him get called up to play for the Telugu Warriors in the inaugural Celebrity Cricket League (CCL) in 2011. Since then he has regularly participated in the CCL tournament, winning the 2016 edition as captain of his team.[7]

Career
As an infant, Akkineni debuted in his father's production, Shiva Nageswara Rao's comedy Sisindri (1995), an Indian adaptation of Baby's Day Out (1994).[8]

In 2014, Akkineni appeared in a cameo in Vikram Kumar's hit family drama Manam (2014), which featured three generations of actors from the Akkineni family. His brief cameo was an instant hit with the audience.[9] He described his shoot for the film alongside his grandfather, father and half-brother, as "nervous and exciting".[10] Manam went on to become as one of the most profitable Telugu films of 2014. Critics dubbed the film as a "classic" en route to it winning several awards, including Best Film at the Filmfare Awards.[11][12] He subsequently went on to make appearances in several commercials, notably for Karbonn, Mountain Dew, and Titan.[13]

Akkineni's debut film as a full-fledged lead was V. V. Vinayak's Akhil (2015).[14] In order to prepare for the role, the actor enrolled in a stunt workshop with his personal trainer Kicha and attended workshops in Thailand for two months.[5] Produced by actor Nithin, the film began production in December 2014 and featured him alongside fellow debutante actress Sayesha Saigal.[15] The film released to poor reviews, and despite expectations, it was a disaster at the box office. Following this, he went on a two-year hiatus. In 2017, his second movie Hello was directed by Vikram Kumar along with Middle Class Abbayi and turned out to be a below par grosser at the box-office, despite garnering good reviews.[16] Akkineni's third project, Mr. Majnu, was directed by Venky Atluri and co-starred Niddhi Agerwal in 2019.[17] In October 2021, his fourth film, a romantic comedy titled Most Eligible Bachelor co starring Pooja Hegde, was released. It was produced by Geetha Arts Bunny Vas and Vasu Varma, and directed by Bhaskar.[18] This film was a hit and gave Akhil the long-awaited box office breakthrough.[19]</h2>
</body>
</html>
